version: '3'
services:
    db:
        image: mysql
        restart: always
        ports:
            - 3307:3306
        environment:
            - MYSQL_DATABSE=wishdb
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - C:\Users\Kishan.dasondhi\mysql_data_docker:/var/lib/mysql
    
    flask-app:
        image: kishanfusion/wish-client
        restart: always
        ports:
            - 5000:5000